package com.htam.agent.runtime;

public enum RuntimeEventType {
    RUN_STARTED,
    RUN_COMPLETED,
    RUN_FAILED,
    MESSAGE_STARTED,
    MESSAGE_DELTA,
    MESSAGE_COMPLETED,
    STEP_STARTED,
    STEP_COMPLETED,
    TOOL_CALL_STARTED,
    TOOL_CALL_ARGUMENTS,
    TOOL_CALL_ENDED,
    TOOL_CALL_COMPLETED,
    TOOL_CALL_FAILED,
    MEMORY_FLUSHED,
    CONTEXT_COMPRESSED,
    DOOM_LOOP_DETECTED,
    FAILURE_RECOVERY_PLANNED,
    APPROVAL_REQUIRED,
    UNKNOWN
}
